const seatingData1 = {
    "maxRow": 13,
    "maxColumn": 21,
    "rows": [
        {
            "name": "M",
            "index": 0,
            "seats": [
                {
                    "id": "10",
                    "area": 1,
                    "column": 0,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 1,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 2,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 3,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 4,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 5,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 6,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 18,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 19,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 20,
                    "row": 0,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "L",
            "index": 1,
            "seats": [
                {
                    "id": "19",
                    "area": 1,
                    "column": 0,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "18",
                    "area": 1,
                    "column": 1,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "17",
                    "area": 1,
                    "column": 2,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "16",
                    "area": 1,
                    "column": 3,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 4,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 5,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 6,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 7,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 8,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 9,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 10,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 11,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 12,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 13,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 14,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 15,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 18,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 19,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 20,
                    "row": 1,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "K",
            "index": 2,
            "seats": [
                {
                    "id": "19",
                    "area": 1,
                    "column": 0,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "18",
                    "area": 1,
                    "column": 1,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "17",
                    "area": 1,
                    "column": 2,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "16",
                    "area": 1,
                    "column": 3,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 4,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 5,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 6,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 7,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 8,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 9,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 10,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 11,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 12,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 13,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 14,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 15,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 18,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 19,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 20,
                    "row": 2,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "J",
            "index": 3,
            "seats": [
                {
                    "id": "19",
                    "area": 1,
                    "column": 0,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "18",
                    "area": 1,
                    "column": 1,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "17",
                    "area": 1,
                    "column": 2,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "16",
                    "area": 1,
                    "column": 3,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 4,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 5,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 6,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 7,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 8,
                    "row": 3,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 9,
                    "row": 3,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 10,
                    "row": 3,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 11,
                    "row": 3,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 12,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 13,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 14,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 15,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 18,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 19,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 20,
                    "row": 3,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "I",
            "index": 4,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 4,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 4,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 4,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "H",
            "index": 5,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 5,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 5,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "G",
            "index": 6,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 6,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 6,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "F",
            "index": 7,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 7,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 7,
                    "status": 1,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 7,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "E",
            "index": 8,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 8,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "D",
            "index": 9,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 9,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "C",
            "index": 10,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 10,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "B",
            "index": 11,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 11,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        },
        {
            "name": "A",
            "index": 12,
            "seats": [
                {
                    "id": "16",
                    "area": 1,
                    "column": 0,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "15",
                    "area": 1,
                    "column": 1,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "14",
                    "area": 1,
                    "column": 2,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "13",
                    "area": 1,
                    "column": 3,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "12",
                    "area": 1,
                    "column": 4,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "11",
                    "area": 1,
                    "column": 5,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "10",
                    "area": 1,
                    "column": 6,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "9",
                    "area": 1,
                    "column": 7,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "8",
                    "area": 1,
                    "column": 8,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "7",
                    "area": 1,
                    "column": 9,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "6",
                    "area": 1,
                    "column": 10,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "5",
                    "area": 1,
                    "column": 11,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "4",
                    "area": 1,
                    "column": 12,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "3",
                    "area": 1,
                    "column": 13,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "2",
                    "area": 1,
                    "column": 14,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                },
                {
                    "id": "1",
                    "area": 1,
                    "column": 15,
                    "row": 12,
                    "status": 0,
                    "ticketPrice": 85000,
                    "categoryCode": "0000000001",
                    "description": "Standard",
                    "type": 1,
                    "seatsInGroup": []
                }
            ]
        }
    ],
    "packages": []
}

export default seatingData1